org: migisha
app: migisha
service: readright-api  # Your service name

provider:
  name: aws
  runtime: nodejs20.x  # Correct Node.js runtime version
  stage: prod
  region: eu-north-1  # AWS region where your Lambda will be deployed

  environment:  # Add all your environment variables here
    HOST: localhost
    AWS_HOST: database-2.c3wsyeq2ezzw.eu-north-1.rds.amazonaws.com
    PORT: 8000
    
    # Database
    MYSQL_USER: root
    MYSQL_PASSWORD: carmel@2023
    MYSQL_DATABASE: readRight
    
    # AWS RDS
    MYSQL_AWS_USER: readright
    MYSQL_AWS_PASSWORD: mEdsHiA1NOdY4BT8oH34
    MYSQL_AWS_DATABASE: readright

    # Email
    SENDER_NAME: Read Right
    SENDER_EMAIL: readright72@gmail.com
    EMAIL_PASSWORD: kope sijp ztsv cfdc

    # Tokens
    ACCESS_TOKEN_SECRET: e98f797658ec14ad28f939505470c506140b07c93f35666b2c961ed5559b088f3e2640b8816cbf60e6c914b87305ad9469bd7292a8eb9757085925d9a0dc57b2
    REFRESH_TOKEN_SECRET: 4bce77b4cfe88aa1e6270acf8301a6fe36de8050362304d396f9d59660b98721190154db69c87be4dac6ac09d987e2584721cb64932771b19f838b103c71b4c4

    # S3 Bucket
    BUCKET_NAME: readright
    BUCKET_REGION: eu-north-1
    ACCESS_KEY: AKIARUJPUFQEHSC22FOU
    SECRET_ACCESS_KEY: DC79Kh4X4C9dcSczPIGmebbrD8dhZJXInR/8jVrh

functions:
  app:
    handler: index.handler  # This points to the handler in your index.js
    events:
      - http:
          path: /
          method: ANY  # Allowing both GET and POST requests
          cors: true 
      - http:
          path: /{proxy+}  # Handles all sub-paths for routes like /api
          method: ANY
          cors: true 
